language: python
python:
  - 3.6.5
services:
  - postgresql
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
script:
  - psql -c 'CREATE DATABASE eretail;' -U postgres
  - pytest
cache: pip
