version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER:eretail
      - POSTGRES_PASSWORD:eretail
      - POSTGRES_DB:eretail
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
