# Generated by Django 3.0.3 on 2020-03-08 18:49

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('order_status', models.CharField(choices=[('cart', 'cart'), ('confirmed', 'confirmed'), ('to_deliver', 'to_deliver'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirm_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=api.models.Sale.order_delivery_date)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('order_status', models.CharField(choices=[('confirmed', 'confirmed'), ('to_deliver', 'to_deliver'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=20)),
                ('product_description', models.TextField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
