# Generated by Django 3.0.3 on 2020-03-03 06:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200302_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('to_deliver', 'to_deliver'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='cart', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_date',
            field=models.DateTimeField(default=api.models.Sale.order_delivery_date),
        ),
    ]
