# Generated by Django 3.0.3 on 2020-03-02 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('order_date', models.DateField(default=datetime.datetime(2020, 3, 2, 10, 36, 35, 278943))),
                ('expected_delivery_date', models.DateField(default=datetime.datetime(2020, 3, 9, 10, 36, 35, 278967))),
                ('order_status', models.CharField(choices=[('cart', 'cart'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
    ]
