# Generated by Django 3.0.3 on 2020-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/images/upload/'),
            preserve_default=False,
        ),
    ]
