# Generated by Django 3.0.3 on 2020-03-02 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 10, 38, 50, 171613)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 2, 10, 38, 50, 171590)),
        ),
    ]
