# Generated by Django 3.0.3 on 2020-03-02 10:44

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200302_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(default=api.models.Order.delivery_time),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 2, 10, 44, 28, 54372)),
        ),
    ]
