# Generated by Django 3.0.3 on 2020-03-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200318_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='main',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='path',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/upload/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Product'),
        ),
    ]
