# Generated by Django 3.0.3 on 2020-03-02 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200302_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 2, 10, 46, 18, 228349)),
        ),
    ]
