# Generated by Django 3.0.3 on 2020-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200318_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
