# Generated by Django 3.0.3 on 2020-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200322_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/upload/images/%Y/%m/%d/'),
        ),
    ]
