# Generated by Django 3.0.3 on 2020-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'customer'), (2, 'small_trader'), (3, 'wholesaler'), (4, 'manufacturer'), (5, 'admin')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
