# Generated by Django 3.0.3 on 2020-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200301_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('trader', 'trader'), ('wholesaler', 'wholesaler'), ('manufacturer', 'manufacturer'), ('admin', 'admin')], max_length=12),
        ),
    ]
