# Generated by Django 3.0.3 on 2020-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200301_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('trader', 'trader'), ('wholesaler', 'wholesaler'), ('manufacturer', 'manufacturer'), ('a', 'admin')], max_length=12),
        ),
    ]
